lannguage: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
 - sudo pip install -r requirements.txt
script:
 - pep8 googlegeocoder
 - pyflakes googlegeocoder
 - python test.py
